Penjelasan tentang indexing pada array 2D

In [3]:
import numpy as np
x=[[4,3,2,1],[1,2,3,4],[5,3,1,0]]
x_ar=np.array(x)

print(x_ar)

[[4 3 2 1]
 [1 2 3 4]
 [5 3 1 0]]


In [5]:
x_s1=x_ar[0][0:4] #baris 0 semua kolom, kolom 0-3
print(x_s1)

[4 3 2 1]


In [7]:
x_s2=x_ar[0:2][0:2] #baris 0-1, kolom 0-1
print(x_s2)

[[4 3 2 1]
 [1 2 3 4]]


In [9]:
x_ar[0:2,0:2]=[[-1,-1],[-2,-2]]
print(x_ar)

[[-1 -1  2  1]
 [-2 -2  3  4]
 [ 5  3  1  0]]


In [10]:
x_s3=x_ar[x_ar>0]
print(x_s3)

[2 1 3 4 5 3 1]


In [11]:
x_s4=x_ar[:,0:1]
print(x_s4)

[[-1]
 [-2]
 [ 5]]


In [12]:
x_s4=x_ar[:,:] #seluruh baris kalau :,:
print(x_s4)

[[-1 -1  2  1]
 [-2 -2  3  4]
 [ 5  3  1  0]]


In [13]:
x_s5=x_ar[:2,0:1] 
print(x_s5)

[[-1]]


In [14]:
x_s5=x_ar[:2,0:1] #:2 artinya baris awal atau s sd (2-1)
print(x_s5)

[[-1]
 [-2]]


In [15]:
x_s5=x_ar[:,:1] #:2 artinya baris awal atau s sd (2-1)
print(x_s5)

[[-1]
 [-2]
 [ 5]]


In [18]:
x_s5=x_ar[:,:2] #:2 artinya baris awal atau s sd (2-1)
print(x_s5)

[[-1 -1]
 [-2 -2]
 [ 5  3]]


In [19]:
x=[[4,3,2,1,0,1,2],[1,2,3,4,-1,-1,-1],[5,3,1,0,-2,-2,-2]]
xa=np.array(x)
print(xa)

[[ 4  3  2  1  0  1  2]
 [ 1  2  3  4 -1 -1 -1]
 [ 5  3  1  0 -2 -2 -2]]


In [21]:
x1=xa[:,:2] #:2 artinya baris awal atau s sd (2-1)
print(x1)
x2=xa[:,:-2] #:-2 artinya kolom yg ditampilkan  tdk termasuk 2 kolom terakhir
print(x2)

[[4 3]
 [1 2]
 [5 3]]
[[ 4  3  2  1  0]
 [ 1  2  3  4 -1]
 [ 5  3  1  0 -2]]


In [26]:
xt=np.transpose(xa) #ukuran awalnya 3x7 emnjadi 7x3
print(xt)
xt.shape

[[ 4  1  5]
 [ 3  2  3]
 [ 2  3  1]
 [ 1  4  0]
 [ 0 -1 -2]
 [ 1 -1 -2]
 [ 2 -1 -2]]


(7, 3)

In [28]:
#mengubah dimensi, tapi tidak mengubah jumlah elemenya
xr=xt.reshape(1,21)
print(xr)
xr.shape

[[ 4  1  5  3  2  3  2  3  1  1  4  0  0 -1 -2  1 -1 -2  2 -1 -2]]


(1, 21)

In [29]:
xr=xt.reshape(21,1)
print(xr)
xr.shape

[[ 4]
 [ 1]
 [ 5]
 [ 3]
 [ 2]
 [ 3]
 [ 2]
 [ 3]
 [ 1]
 [ 1]
 [ 4]
 [ 0]
 [ 0]
 [-1]
 [-2]
 [ 1]
 [-1]
 [-2]
 [ 2]
 [-1]
 [-2]]


(21, 1)

In [39]:
#perintah if
x=1
if(x==1):
    print("x adalah",x)
elif(x==2):
    print("x adalah",x)
else:
    print("x bukan 1 dan 2")


x adalah 1


In [34]:
x=10
if(x==1):
    print(x)
elif(x==2):
    print(x)
else:
    print("x bukan 1 dan 2")

x bukan 1 dan 2


In [40]:
#perintah if
x=2
if(x==1):
    print("x adalah",x)
elif(x==2):
    print("x adalah",x)
else:
    print("x bukan 1 dan 2")

x adalah 2


In [41]:
import pandas as pd

file='epl-goalScorer(20-21).csv'
db=pd.read_csv(file) #menampilkan 5 baris teratas dan 5 baris terbawah
#ada 521 row
print (db)

     Unnamed: 0    id             player_name  games  time  goals         xG  \
0             0   647              Harry Kane     35  3097     23  22.174859   
1             1  1250           Mohamed Salah     37  3085     22  20.250847   
2             2  1228         Bruno Fernandes     37  3117     18  16.019454   
3             3   453           Son Heung-Min     37  3139     17  11.023287   
4             4   822         Patrick Bamford     38  3085     17  18.401863   
..          ...   ...                     ...    ...   ...    ...        ...   
517         517  9415  Jaden Philogene-Bidace      1     1      0   0.000000   
518         518  9423         Gaetano Berardi      2   113      0   0.074761   
519         519  9524          Anthony Elanga      1    67      0   0.000000   
520         520  9540             Femi Seriki      1     1      0   0.000000   
521         521  9552         Tyrese Francois      1    13      0   0.000000   

     assists         xA  shots  key_pas

In [46]:
print (db.dtypes) #tipe data dari masing" kolom

Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object


In [42]:
db.head() #5baris teratas

Unnamed: 0    id      player_name  games  time  goals         xG  assists  \
0           0   647       Harry Kane     35  3097     23  22.174859       14   
1           1  1250    Mohamed Salah     37  3085     22  20.250847        5   
2           2  1228  Bruno Fernandes     37  3117     18  16.019454       12   
3           3   453    Son Heung-Min     37  3139     17  11.023287       10   
4           4   822  Patrick Bamford     38  3085     17  18.401863        7   

          xA  shots  key_passes  yellow_cards  red_cards position  \
0   7.577094    138          49             1          0        F   
1   6.528526    126          55             0          0    F M S   
2  11.474996    121          95             6          0      M S   
3   9.512992     68          75             0          0    F M S   
4   3.782247    107          30             3          0      F S   

          team_title  npg       npxG    xGChain  xGBuildup  
0          Tottenham   19  19.130183  24.995648   4.451257  
1          Liverpool   16  15.683834  28.968234   9.800236  
2  Manchester United    9   8.407840  26.911412  11.932285  
3          Tottenham   16  10.262118  20.671916   6.608751  
4              Leeds   15  16.879525  23.394953   4.131796

In [44]:
db.tail() #5 baris terbawah

Unnamed: 0    id             player_name  games  time  goals        xG  \
517         517  9415  Jaden Philogene-Bidace      1     1      0  0.000000   
518         518  9423         Gaetano Berardi      2   113      0  0.074761   
519         519  9524          Anthony Elanga      1    67      0  0.000000   
520         520  9540             Femi Seriki      1     1      0  0.000000   
521         521  9552         Tyrese Francois      1    13      0  0.000000   

     assists   xA  shots  key_passes  yellow_cards  red_cards position  \
517        0  0.0      0           0             0          0        S   
518        0  0.0      1           0             0          0      D S   
519        0  0.0      0           0             0          0        M   
520        0  0.0      0           0             0          0        S   
521        0  0.0      0           0             0          0        S   

            team_title  npg      npxG   xGChain  xGBuildup  
517        Aston Villa    0  0.000000  0.056044   0.056044  
518              Leeds    0  0.074761  0.231278   0.231278  
519  Manchester United    0  0.000000  0.000000   0.000000  
520   Sheffield United    0  0.000000  0.000000   0.000000  
521             Fulham    0  0.000000  0.000000   0.000000

In [47]:
#menampilkan matriks pada pandas
print(db.iloc[3,1])

453


In [49]:
print(db.iloc[2:4,0:4]) #

   Unnamed: 0    id      player_name  games
2           2  1228  Bruno Fernandes     37
3           3   453    Son Heung-Min     37


In [50]:
db.describe() #hanya berlaku untuk tipe yg numerik (float dan int) saja, untuk strik tidak bisa dihitung

Unnamed: 0           id       games         time       goals  \
count  522.000000   522.000000  522.000000   522.000000  522.000000   
mean   260.500000  4380.932950   19.643678  1420.068966    1.862069   
std    150.832689  3281.776121   11.619836  1031.604819    3.338851   
min      0.000000    65.000000    1.000000     1.000000    0.000000   
25%    130.250000   839.750000   10.000000   470.250000    0.000000   
50%    260.500000  4627.000000   21.000000  1342.000000    1.000000   
75%    390.750000  7690.500000   30.000000  2319.000000    2.000000   
max    521.000000  9552.000000   38.000000  3420.000000   23.000000   

               xG     assists          xA       shots  key_passes  \
count  522.000000  522.000000  522.000000  522.000000  522.000000   
mean     2.000806    1.289272    1.376029   17.379310   12.963602   
std      3.317946    2.083350    1.886510   21.572664   16.164361   
min      0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.074668    0.000000    0.049245    2.000000    1.000000   
50%      0.737295    0.000000    0.691122   10.000000    7.000000   
75%      2.053378    2.000000    2.050509   23.750000   19.000000   
max     22.174859   14.000000   11.474996  138.000000   95.000000   

       yellow_cards   red_cards         npg        npxG     xGChain  \
count    522.000000  522.000000  522.000000  522.000000  522.000000   
mean       2.061303    0.091954    1.668582    1.821450    5.663368   
std        2.203661    0.295800    2.909929    2.931176    5.600249   
min        0.000000    0.000000    0.000000    0.000000    0.000000   
25%        0.000000    0.000000    0.000000    0.074668    1.191391   
50%        2.000000    0.000000    0.500000    0.715585    4.252738   
75%        3.000000    0.000000    2.000000    1.945799    8.308002   
max       12.000000    2.000000   19.000000   19.130183   28.968234   

        xGBuildup  
count  522.000000  
mean     3.455060  
std      3.376584  
min      0.000000  
25%      0.720353  
50%      2.656397  
75%      5.254647  
max     18.323006

In [53]:
 #dapat menampilkan tidak hanya numerik, namun juga string, hanya saja tidak bisa dihitung bagian rata" (mean), standart defiasi (std)
#yg paling sering muncul disana terlihat pada bagian TOP yaitu harry kane
#menghasilkan NaN karena tidak terhitung stringnya disana
db.describe(include = 'all')

Unnamed: 0           id player_name       games         time  \
count   522.000000   522.000000         522  522.000000   522.000000   
unique         NaN          NaN         522         NaN          NaN   
top            NaN          NaN  Harry Kane         NaN          NaN   
freq           NaN          NaN           1         NaN          NaN   
mean    260.500000  4380.932950         NaN   19.643678  1420.068966   
std     150.832689  3281.776121         NaN   11.619836  1031.604819   
min       0.000000    65.000000         NaN    1.000000     1.000000   
25%     130.250000   839.750000         NaN   10.000000   470.250000   
50%     260.500000  4627.000000         NaN   21.000000  1342.000000   
75%     390.750000  7690.500000         NaN   30.000000  2319.000000   
max     521.000000  9552.000000         NaN   38.000000  3420.000000   

             goals          xG     assists          xA       shots  \
count   522.000000  522.000000  522.000000  522.000000  522.000000   
unique         NaN         NaN         NaN         NaN         NaN   
top            NaN         NaN         NaN         NaN         NaN   
freq           NaN         NaN         NaN         NaN         NaN   
mean      1.862069    2.000806    1.289272    1.376029   17.379310   
std       3.338851    3.317946    2.083350    1.886510   21.572664   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       0.000000    0.074668    0.000000    0.049245    2.000000   
50%       1.000000    0.737295    0.000000    0.691122   10.000000   
75%       2.000000    2.053378    2.000000    2.050509   23.750000   
max      23.000000   22.174859   14.000000   11.474996  138.000000   

        key_passes  yellow_cards   red_cards position team_title         npg  \
count   522.000000    522.000000  522.000000      522        522  522.000000   
unique         NaN           NaN         NaN       14         28         NaN   
top            NaN           NaN         NaN      M S    Everton         NaN   
freq           NaN           NaN         NaN      106         28         NaN   
mean     12.963602      2.061303    0.091954      NaN        NaN    1.668582   
std      16.164361      2.203661    0.295800      NaN        NaN    2.909929   
min       0.000000      0.000000    0.000000      NaN        NaN    0.000000   
25%       1.000000      0.000000    0.000000      NaN        NaN    0.000000   
50%       7.000000      2.000000    0.000000      NaN        NaN    0.500000   
75%      19.000000      3.000000    0.000000      NaN        NaN    2.000000   
max      95.000000     12.000000    2.000000      NaN        NaN   19.000000   

              npxG     xGChain   xGBuildup  
count   522.000000  522.000000  522.000000  
unique         NaN         NaN         NaN  
top            NaN         NaN         NaN  
freq           NaN         NaN         NaN  
mean      1.821450    5.663368    3.455060  
std       2.931176    5.600249    3.376584  
min       0.000000    0.000000    0.000000  
25%       0.074668    1.191391    0.720353  
50%       0.715585    4.252738    2.656397  
75%       1.945799    8.308002    5.254647  
max      19.130183   28.968234   18.323006

In [54]:
#menghitung rata"
db.mean()
#adanya warning, karena ada string, shg muncul bgt

C:\Users\dinir\AppData\Local\Temp/ipykernel_9672/3490540417.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  db.mean()


Unnamed: 0       260.500000
id              4380.932950
games             19.643678
time            1420.068966
goals              1.862069
xG                 2.000806
assists            1.289272
xA                 1.376029
shots             17.379310
key_passes        12.963602
yellow_cards       2.061303
red_cards          0.091954
npg                1.668582
npxG               1.821450
xGChain            5.663368
xGBuildup          3.455060
dtype: float64

In [55]:
db.std()

C:\Users\dinir\AppData\Local\Temp/ipykernel_9672/2636834045.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  db.std()


Unnamed: 0       150.832689
id              3281.776121
games             11.619836
time            1031.604819
goals              3.338851
xG                 3.317946
assists            2.083350
xA                 1.886510
shots             21.572664
key_passes        16.164361
yellow_cards       2.203661
red_cards          0.295800
npg                2.909929
npxG               2.931176
xGChain            5.600249
xGBuildup          3.376584
dtype: float64

In [56]:
db.quantile(0.9)

Unnamed: 0       468.900000
id              8722.900000
games             35.000000
time            2879.100000
goals              6.000000
xG                 5.849947
assists            4.000000
xA                 3.739705
shots             46.000000
key_passes        34.900000
yellow_cards       5.000000
red_cards          0.000000
npg                5.000000
npxG               5.494491
xGChain           13.888492
xGBuildup          8.115947
Name: 0.9, dtype: float64

In [58]:
q1=db.quantile(0.25)
q3=db.quantile(0.75)
iqr=q3-q1
print(iqr)

Unnamed: 0       260.500000
id              6850.750000
games             20.000000
time            1848.750000
goals              2.000000
xG                 1.978711
assists            2.000000
xA                 2.001264
shots             21.750000
key_passes        18.000000
yellow_cards       3.000000
red_cards          0.000000
npg                2.000000
npxG               1.871131
xGChain            7.116612
xGBuildup          4.534294
dtype: float64


In [63]:
#mencari nilai pencilan
pencilan=(db<q1-1.5*iqr) | (db>q3+1.5*iqr)
print(pencilan)



     Unnamed: 0  assists  games  goals     id  key_passes    npg   npxG  \
0         False     True  False   True  False        True   True   True   
1         False    False  False   True  False        True   True   True   
2         False     True  False   True  False        True   True   True   
3         False     True  False   True  False        True   True   True   
4         False     True  False   True  False       False   True   True   
..          ...      ...    ...    ...    ...         ...    ...    ...   
517       False    False  False  False  False       False  False  False   
518       False    False  False  False  False       False  False  False   
519       False    False  False  False  False       False  False  False   
520       False    False  False  False  False       False  False  False   
521       False    False  False  False  False       False  False  False   

     player_name  position  red_cards  shots  team_title   time     xA     xG  \
0          False  

C:\Users\dinir\AppData\Local\Temp/ipykernel_9672/717122818.py:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  pencilan=(db<q1-1.5*iqr) | (db>q3+1.5*iqr)


In [65]:
#value counts adalah jumlah string yg muncul
db.value_counts()

Unnamed: 0  id    player_name             games  time  goals  xG         assists  xA        shots  key_passes  yellow_cards  red_cards  position  team_title                    npg  npxG       xGChain    xGBuildup
0           647   Harry Kane              35     3097  23     22.174859  14       7.577094  138    49          1             0          F         Tottenham                     19   19.130183  24.995648  4.451257     1
358         1823  Lucas Digne             29     2593  0      0.449756   7        5.960717  12     45          2             1          D M       Everton                       0    0.449756   10.744329  6.589036     1
356         1760  Arthur Masuaku          12     1017  0      0.429026   2        2.595892  6      11          2             0          D M       West Ham                      0    0.429026   4.273891   1.791140     1
355         1750  Ainsley Maitland-Niles  26     1719  0      0.796191   0        0.821991  12     6           2             0       

In [66]:
#
db['player_name'].value_counts()

Harry Kane                1
Lucas Digne               1
Arthur Masuaku            1
Ainsley Maitland-Niles    1
Rob Holding               1
                         ..
Manuel Lanzini            1
Cheikhou Kouyaté          1
Scott Dann                1
Alex Iwobi                1
Tyrese Francois           1
Name: player_name, Length: 522, dtype: int64

In [67]:
db['team_title'].value_counts()

Everton                          28
West Bromwich Albion             28
Sheffield United                 27
Southampton                      27
Manchester United                27
Fulham                           27
Leicester                        27
Wolverhampton Wanderers          27
Liverpool                        27
Brighton                         26
Arsenal                          26
Newcastle United                 26
Burnley                          25
Chelsea                          25
Crystal Palace                   24
Manchester City                  24
Tottenham                        24
West Ham                         23
Aston Villa                      23
Leeds                            23
Arsenal,Newcastle United          1
Everton,Southampton               1
Aston Villa,Chelsea               1
Liverpool,Southampton             1
Chelsea,Fulham                    1
West Bromwich Albion,West Ham     1
Arsenal,West Bromwich Albion      1
Arsenal,Brighton            

In [69]:
#korelasi/hubungan antara 1 kolom dengan kolom lain
#saat kolom yg sama dihitung, maka nanti hasilnya akan 1 karena dia sama
#makin tinggi nilai korelasi, maka makin terkait
#seperti waktu dan permainan memiliki nilai korelasi yg tinggi karena memiliki hubungan yg cukup tinggi
#makin mendekati 0, makins edikit hubungannya
#jika bernilai -, dia berhubungan tapi berkebalikan

db.corr()

Unnamed: 0        id     games      time     goals        xG  \
Unnamed: 0      1.000000  0.434277 -0.571683 -0.484440 -0.719526 -0.670802   
id              0.434277  1.000000 -0.208828 -0.177752 -0.151258 -0.153850   
games          -0.571683 -0.208828  1.000000  0.944591  0.439730  0.463869   
time           -0.484440 -0.177752  0.944591  1.000000  0.398930  0.411203   
goals          -0.719526 -0.151258  0.439730  0.398930  1.000000  0.932798   
xG             -0.670802 -0.153850  0.463869  0.411203  0.932798  1.000000   
assists        -0.512642 -0.185824  0.504168  0.473555  0.617490  0.636205   
xA             -0.550027 -0.152126  0.562806  0.516638  0.607330  0.627495   
shots          -0.716971 -0.142156  0.599164  0.529534  0.873363  0.910214   
key_passes     -0.550549 -0.144589  0.617867  0.575065  0.567752  0.570488   
yellow_cards   -0.238503 -0.058407  0.565963  0.592223  0.097151  0.093761   
red_cards      -0.096709 -0.019094  0.160326  0.186333  0.053679  0.048815   
npg            -0.727651 -0.137526  0.437110  0.392631  0.971591  0.894286   
npxG           -0.672051 -0.141015  0.465546  0.408231  0.905710  0.979218   
xGChain        -0.660299 -0.188079  0.726598  0.703801  0.727953  0.763909   
xGBuildup      -0.417677 -0.161435  0.697196  0.731377  0.290990  0.282746   

               assists        xA     shots  key_passes  yellow_cards  \
Unnamed: 0   -0.512642 -0.550027 -0.716971   -0.550549     -0.238503   
id           -0.185824 -0.152126 -0.142156   -0.144589     -0.058407   
games         0.504168  0.562806  0.599164    0.617867      0.565963   
time          0.473555  0.516638  0.529534    0.575065      0.592223   
goals         0.617490  0.607330  0.873363    0.567752      0.097151   
xG            0.636205  0.627495  0.910214    0.570488      0.093761   
assists       1.000000  0.885850  0.721220    0.835299      0.209349   
xA            0.885850  1.000000  0.759568    0.946506      0.243912   
shots         0.721220  0.759568  1.000000    0.743370      0.249957   
key_passes    0.835299  0.946506  0.743370    1.000000      0.343357   
yellow_cards  0.209349  0.243912  0.249957    0.343357      1.000000   
red_cards    -0.021444  0.006284  0.073932    0.022780      0.165064   
npg           0.587316  0.585152  0.852989    0.539726      0.093270   
npxG          0.615503  0.611100  0.901386    0.545537      0.089065   
xGChain       0.752587  0.814487  0.843152    0.807958      0.401884   
xGBuildup     0.473254  0.547983  0.448197    0.618754      0.562467   

              red_cards       npg      npxG   xGChain  xGBuildup  
Unnamed: 0    -0.096709 -0.727651 -0.672051 -0.660299  -0.417677  
id            -0.019094 -0.137526 -0.141015 -0.188079  -0.161435  
games          0.160326  0.437110  0.465546  0.726598   0.697196  
time           0.186333  0.392631  0.408231  0.703801   0.731377  
goals          0.053679  0.971591  0.905710  0.727953   0.290990  
xG             0.048815  0.894286  0.979218  0.763909   0.282746  
assists       -0.021444  0.587316  0.615503  0.752587   0.473254  
xA             0.006284  0.585152  0.611100  0.814487   0.547983  
shots          0.073932  0.852989  0.901386  0.843152   0.448197  
key_passes     0.022780  0.539726  0.545537  0.807958   0.618754  
yellow_cards   0.165064  0.093270  0.089065  0.401884   0.562467  
red_cards      1.000000  0.055542  0.047354  0.104005   0.167660  
npg            0.055542  1.000000  0.913496  0.720978   0.284135  
npxG           0.047354  0.913496  1.000000  0.763481   0.273090  
xGChain        0.104005  0.720978  0.763481  1.000000   0.802073  
xGBuildup      0.167660  0.284135  0.273090  0.802073   1.000000

In [70]:
#groupby menggrubkan antar kolom
db.groupby('team_title')['goals'].mean()

team_title
Arsenal                          1.961538
Arsenal,Brighton                 0.000000
Arsenal,Newcastle United         8.000000
Arsenal,West Bromwich Albion     0.000000
Aston Villa                      2.130435
Aston Villa,Chelsea              3.000000
Brighton                         1.500000
Burnley                          1.280000
Chelsea                          2.240000
Chelsea,Fulham                   1.000000
Crystal Palace                   1.625000
Everton                          1.607143
Everton,Southampton              3.000000
Fulham                           0.925926
Leeds                            2.608696
Leicester                        2.370370
Liverpool                        2.370370
Liverpool,Southampton            3.000000
Manchester City                  3.208333
Manchester United                2.518519
Newcastle United                 1.384615
Sheffield United                 0.666667
Southampton                      1.555556
Tottenham              

In [72]:
db.groupby('team_title')['goals'].mean().sort_values(ascending=True)

team_title
Arsenal,Brighton                 0.000000
West Bromwich Albion,West Ham    0.000000
Arsenal,West Bromwich Albion     0.000000
Sheffield United                 0.666667
Fulham                           0.925926
Chelsea,Fulham                   1.000000
West Bromwich Albion             1.178571
Wolverhampton Wanderers          1.222222
Burnley                          1.280000
Newcastle United                 1.384615
Brighton                         1.500000
Southampton                      1.555556
Everton                          1.607143
Crystal Palace                   1.625000
Arsenal                          1.961538
Aston Villa                      2.130435
Chelsea                          2.240000
Leicester                        2.370370
Liverpool                        2.370370
West Ham                         2.478261
Manchester United                2.518519
Leeds                            2.608696
Tottenham                        2.750000
Aston Villa,Chelsea    

In [73]:
db.groupby('team_title')['goals'].mean().sort_values(ascending=False)

team_title
Arsenal,Newcastle United         8.000000
Manchester City                  3.208333
Aston Villa,Chelsea              3.000000
Liverpool,Southampton            3.000000
Everton,Southampton              3.000000
Tottenham                        2.750000
Leeds                            2.608696
Manchester United                2.518519
West Ham                         2.478261
Leicester                        2.370370
Liverpool                        2.370370
Chelsea                          2.240000
Aston Villa                      2.130435
Arsenal                          1.961538
Crystal Palace                   1.625000
Everton                          1.607143
Southampton                      1.555556
Brighton                         1.500000
Newcastle United                 1.384615
Burnley                          1.280000
Wolverhampton Wanderers          1.222222
West Bromwich Albion             1.178571
Chelsea,Fulham                   1.000000
Fulham                 

yey selesai di jam 15:03